# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 04:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_amount', models.DecimalField(decimal_places=0, max_digits=13)),
                ('amount_date', models.DateField()),
                ('user', models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=250)),
                ('vendor_number', models.CharField(max_length=50)),
                ('bill_number', models.CharField(max_length=250)),
                ('receipt_number', models.CharField(max_length=250)),
                ('employee_payment', models.DecimalField(decimal_places=0, max_digits=13)),
                ('pension_payment', models.DecimalField(decimal_places=0, max_digits=13)),
                ('payment_date', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_problem', models.CharField(max_length=500)),
                ('verification_date', models.DateField()),
                ('anggaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagihan.Anggaran')),
            ],
            options={
                'permissions': (('change_is_verified', 'Can edit verification'), ('fill_is_problem', 'Can fill problem form'), ('view_is_verified', 'Can view verification'), ('view_is_problem', 'Can view problem'), ('print_output', 'Can Print Report'), ('can_login', 'Can Login to Index')),
            },
        ),
    ]
