# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagihan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='is_problem',
            field=models.CharField(default='Tidak Ada', max_length=500),
        ),
    ]
