# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagihan', '0003_auto_20170217_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='is_problem',
            field=models.CharField(blank=True, default='Tidak Ada', max_length=500, null=True),
        ),
    ]
