# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagihan', '0004_auto_20170217_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='provider_name',
            field=models.CharField(max_length=500),
        ),
    ]
