# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagihan', '0005_auto_20170217_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pembayaran',
            options={'permissions': (('change_is_verified', 'Can edit verification'), ('fill_is_problem', 'Can fill problem form'), ('view_is_verified', 'Can view verification'), ('view_is_problem', 'Can view problem'), ('print_output', 'Can Print Report'), ('can_login', 'Can Login to Index'), ('is_administration', 'User is Administration'), ('is_keuangan', 'User is Keuangan'))},
        ),
    ]
