# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagihan', '0007_auto_20170217_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='employee_payment',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='pension_payment',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True),
        ),
    ]
